language: rust

rust:
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

before_install:
  - rvm install 2.3.0
  - gem install bundler
  - bundle install

install:
  - ruby ext/extconf.rb
  - make

script:
  - bundle exec rspec
